name: Greetings

on: # [pull_request, issues,push]
  push:
   branches:
      - master
      - test
  

jobs:
  greeting:
    runs-on: windows-latest
    

    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        run: echo Hello World $FIRST_NAME $middle_name $Last_Name!         
        # echo 'The time was ${{ steps.hello.outputs.time }}.'
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat
       
        
